### PR TITLE
Travis: Use trusty

### PR DESCRIPTION
**Pull request by mllg**

### CODE REVIEW

**Comment by berndbischl** [comment]
short reason? why is trusty cooler?

**Comment by mllg** [comment]
You have a modern compiler with C++11 support. Not (yet) needed for mlrMBO, but nevertheless good to have for the future as ranger uses C++11.

**Comment by berndbischl** [comment]
use in mlr to make travis script shorter? isnt it more important there?

**Comment by mllg** [comment]
For mlr we would need this first: https://github.com/travis-ci/apt-package-whitelist/issues/4017

**Pull request merged**
