### PR TITLE
mboLoop: documentation and clean-up (Issue #131)

### PR DESCRIPTION
**Pull request by jakob-r**
Please let me now if you have further questions to be answered in the code or specific requests how to document.

### CODE REVIEW

**Comment by berndbischl** [comment]
Can you please outline BRIEFLY what you did? Some code parts seem to have disappeared, I guess because they where suboptimal?

Although we REALLY need a running travis again. Otherwise we cannot check this stuff properly.

**Comment by berndbischl** [comment]
Shall we maybe disable the unit test / examples where ggally is triggered? And open up a issue for this so we dont forget to reeanable this?

**Comment by jakob-r** [comment]
I deleted a tiny fraction because it simply wasn't used. Some parts I just moved to a more logic poistion. You can comment directly on the specific lines in the diff if you have specific questions.
One change is, that I separated the creation of an initial design from the evaluation / writing in the opt path so we have a design we can safely get via `getOptProblemDesign`.

**Comment by berndbischl** [comment]
Ok, thanks. 

But in general please always - for changes such like this - really add in the PR a FEW sentences describing what you did. With such a mini guideline it is MUCH easier to read an review. 

I will read later and try to merge. 

What about my question for the tests?

**Comment by jakob-r** [comment]
I fully understand regarding the description of changes. Tests will pass again thanks to a quick response of the ggally team. I restarted all Travis Checks.

**Comment by berndbischl** [comment]
Cool thx. I hope I can merge this today, just want to read it once.
I iwill hurry up

**Comment by berndbischl** [comment]
Looks good. Merging. 
Please rename about 3 functions, so "Design" becomes "InitDesign".

**Pull request merged**
