### PR TITLE
suggestions for DIB

### PR DESCRIPTION
**Pull request by jakob-r**
Maybe we can reimplement the random lambda stuff. But we should to it right.

Also: Do multi point proposals work with constant lambda but with the changed opt Path? Or is it more a constant believer where the CB is the lie? That's how it looks to me. This should be documented in `setMBOControlMultiPoint` although it looks like I am not supposed to set something there when I do multi-point with DIB, right?

### CODE REVIEW

**Comment by berndbischl** [comment]
issue seems to be here #345 

please read what i said there, we can continue talking here.

**Comment by jakob-r** [comment]
@danielhorn can you please look into it? I don't see so easily how DIB is supposed to work with multipoint proposals. That is also where it fails now.

**Comment by danielhorn** [comment]
Next week, Melanie and I are moving on thursday, and, it's all realy stressful at the moment :(

**Comment by danielhorn** [comment]
Ok, I think I found it. Let me try to explain it:

DIB is a specialized multi.obj criterion. It fits one model  per objective. The infill criterion now calculates the CB value for each objective - we have a vector of CB values now. The DIB value is now the (hypervolume) contribution of this vector to the current Pareto front approximation.

For the multipoint approach we use the constant liar idea: For the first point, use standard DIB. Then calculate the CB values of the proposed point and add this point and its CB values to a fake opt.path, and propose the next point based on this fake opt.path. Since the fake point changes the Pareto front, and DIB is based on the Pareto front, the next proposed point will be different.

What does this mean for your code?
1) As long as we do use the same lambda for each proposed point, you do not have to create a list of control objects in line 25. A single one is enough, but you have to create a new one since propose.points = 1 must be set.
2) In line 32 this single new control object must be used to propose a new point via DIB.
3) In line 34 you have to use makeMBOInfillCritCB()$fun instead of DIB$fun. And make sure, that the same lambda-values are used as in line 32. Since we have to add the CB values to the fake opt.path, not the DIB value.

We could discuss, if DIB should also return the CB values it uses

**Comment by jakob-r** [comment]
> We could discuss, if DIB should also return the CB values it uses
Nice to have but no must.

For the code changes you want to look into that? otherwise assign me.

**Comment by danielhorn** [comment]
Done and pushed

**Comment by jakob-r** [comment]
Thanks! Looks good!

**Comment by berndbischl** [comment]
hi, comments:

- why do you refactor: createSinglePointControls, and now dont use it in proposePointsDIB.R
the function should have an option to create multiple controls with a user given lambda

- it seems EXTREMLY error prone to create the random lambdas like you are doing in createSinglePointControls? it is not even visible that this is done. and if we change our defaults, we now break the DIB algo?

- cbFun is not stlye giude

**Comment by berndbischl** [comment]
> why do you refactor: createSinglePointControls, and now dont use it in proposePointsDIB.R
> the function should have an option to create multiple controls with a user given lambda

ok, this might be ok, as we only need one object as daniel said, above.

> it seems EXTREMLY error prone to create the random lambdas like you are doing in createSinglePointControls? it is not even visible that this is done. and if we change our defaults, we now break the DIB algo?

well, the API docs for the function are wrong. which is why i misunderstood what happens here.

>>> create control objects with random lamda values for parallel cb multi-point

apparently this sentence does not hold anymore. can we please stop doing that? REALLY check input-output type of docs?

**Pull request merged**
