### PR TITLE
default EA params depend on number of parameters

### PR DESCRIPTION
**Pull request by jakobbossek**

### CODE REVIEW

**Comment by jakob-r** [comment]
Do we really need the set.by.user flag? Why don't we just set it to NULL if the user didn't give any input?

**Comment by berndbischl** [comment]
also doc seem to be missing for the default

**Comment by jakob-r** [comment]
rebased and added documentation (1 sentence)

**Comment by jakobbossek** [comment]
I think we are fine here now.

**Comment by berndbischl** [comment]
thx

**Pull request merged**
