### PR TITLE
Fix149 proposed points type in optpath

### PR DESCRIPTION
**Pull request by jakobbossek**
* added prop.type column to optPath
* named stuff as discussed in #149 
* documented possible prop.type values in optpath docs

### CODE REVIEW

**Comment by jakob-r** [comment]
Looks good. Thanks also for cleaning up a bit the multifid stuff.

**Comment by jakobbossek** [comment]
ping

**Comment by mllg** [comment]
I'm unsure what @berndbischl thinks about the underscore in the names, but it can easily be fixed later if necessary. Thanks!.

**Comment by berndbischl** [comment]
do refer to the names of the types? underscores here are totally fine here IMHO, as long as the types themselves are docimented

**Comment by berndbischl** [comment]
and as you can read here, devtools sets this. 
http://www.inside-r.org/packages/cran/devtools/docs/r_env_vars

**Comment by berndbischl** [comment]
so the enir var does indeed exist.

**Pull request merged**
