### PR TITLE
lcb.lambda can be taken as parameter of rexp in multipoint

### PR DESCRIPTION
**Pull request by jakob-r**
To obtain randomly choosen lambdas we use the multipoint method as a shortcut.

### CODE REVIEW

**Comment by berndbischl** [comment]
I would like to discuss this on hangout before I merge this, I might have a better idea

**Comment by berndbischl** [comment]
Please see my comment above.

**Comment by jakob-r** [comment]
everything fine now - ready to be pulled

**Comment by berndbischl** [comment]
getExtras: 
Why have you removed the explicit check in the "if" for proposedpoints > 1?

Docs:
" If you use \code{lcb} as a \code{MultiPoint}-Method, this value will be the expected value of the exponetial distribution from which the multiple Lambda-parameters will be drawn. "

Please check your spelling and English. I can spot >= 3 errors in a single sentence.
- English does not use hyphens as often as German
- method is lower case
- lamba
- exponetial

**Comment by jakob-r** [comment]
I removed `control$propose.points > 1L` because it's kind of redundant with `control$multipoint.method == "lcb"`. If you want the user to only use a multipoint.method when `propose.points > 1` then we should check it earlier. We also already discussed, that i like to have the ability to use random lcb values for only one proposed point which will be possible this way.

Spelling should be fixed.

**Comment by berndbischl** [comment]
> I removed control$propose.points > 1L because it's kind of redundant with

Can you pls add this again? I have used this in 1 million other places to distinguish between single point and multipoint cases. You cannot do such changes only in one place without defining this properly and talking about it. 

And the check should be the other way round. If the user requests a multipoint method, an error should be generated, if propose.points is = 1.

If you want the random lambda selection for lcb, properly define, doc and test it and we can merge this too. but we dont want a hack. 

You are welcome to discuss the potential change here first.

**Comment by jakob-r** [comment]
> And the check should be the other way round. If the user requests a multipoint method, an error should be generated, if propose.points is = 1.

Exactly. That's why it should be done in `setMBOControlMultiPoint.R` and not somewhere in the code, when it's "too late".
Also we are talking about the `extras` for the opt.path. So if you really want to make sure that `propose.points > 1` then you should have done it earlier but you didn't. We have this extra information as soon as `proposePointsParallelLCB` is called which is the case already when `number.of.targets == 1 && control$multipoint.method == "lcb"`. See [here](https://github.com/berndbischl/mlrMBO/blob/master/R/proposePoints.R#L28). So why now doing a different check?

> I have used this in 1 million other places to distinguish between single point and multipoint cases.

I don't know if this reason satisfies me so much. But anyhow here we do not need that differentiation.

> we dont want a hack

Then we have to rewrite major parts of mlrMBO. Again, it is not a hack it give's the user the option to hack.

**Comment by berndbischl** [comment]
You are really talking in generalities.

Concrete things:

1) Do you want to enable random lambda sampling for simple point proposal?
If the answer is yes, you have not even documented this. 

2) I really want to have a check for:
"If the user requests a multipoint method, an error should be generated, if propose.points is = 1."
Yes, of course in the beginning either the control or "checkStuff"
Could you please add this in the PR?

**Pull request closed without merging**
