### PR TITLE
Fix se infillCrit

### PR DESCRIPTION
**Pull request by ja-thomas**
See #325 

What happened:

- `getInfillCritFunction` has a `match.fun` argument (I guess for user defined criteria).
- The id of `makeMBOInfillCriterionStandardError` was set to `sd` instead of `se`
- Well as `sd` is a valid function in R, `getInfillCritFunction` matched that and returned the sd function.

Is fixed now and we also test `makeMBOInfillCriterionStandardError` in the tests now...

EDIT: 

Maybe we should add a check in the end of `getInfillCritFunction`, that the object returned by match.fun has class `"MBOInfillCriterion"`

### CODE REVIEW

**Comment by ja-thomas** [comment]
One question:

I'm not sure about minimization/maximization for `makeMBOInfillCriterionStandardError`, is there a situation in which we want to minimize the SE? I guess not, as this would in most cases mean to suggest only already evaluated points...

**Comment by jakob-r** [comment]
The minus was correct because internally we always minimize the infill. And as we want to maximize the se we have to put the minus.

**Comment by berndbischl** [comment]
you want to max the SE, that is exploration.
i cannot think of another usecase for now, and if it comes up you can now easily overwrite our internal choices here or create your completely custom infill

**Comment by berndbischl** [comment]
just merge this pls

**Pull request merged**
