### PR TITLE
better makeMboLearner

### PR DESCRIPTION
**Pull request by berndbischl**

### CODE REVIEW

**Comment by berndbischl** [comment]
@jakob-r @ja-thomas 
pls review

**Comment by jakobbossek** [comment]
Looks good to me 👍

**Comment by berndbischl** [comment]
@mllg 
pls review + merge

**Comment by mllg** [comment]
Looks good!

**Comment by jakob-r** [comment]
I don't like this because in **mlr** we wanted to go more into the direction where `setHyperPars(...)` is not used to *update* some parameters but to really *set* those HyperPars.

**Pull request merged**
