### PR TITLE
add max evals stopping condition

### PR DESCRIPTION
**Pull request by jakobbossek**

### CODE REVIEW

**Comment by jakob-r** [comment]
Please wait with merge - i will suggest some minor changes

**Comment by berndbischl** [comment]
noted

**Comment by jakob-r** [comment]
was really minor, done

**Comment by jakobbossek** [comment]
Thanks @jakob-r

**Comment by berndbischl** [comment]
things to fix after merge:
max.evals default not doced
makeMBOTerminationMaxEvals is a better naming scheme -> command completion

**Comment by berndbischl** [comment]
is it doced how or$final.state works?

**Comment by jakob-r** [comment]
The defaults are pretty obvious: If they are not given the stopping crit is not taken into account. Should we really add something like "NULL means * won't stop mbo"

**Comment by berndbischl** [comment]
> Should we really add something like "NULL means * won't stop mbo"

Yes we should. lets be formal about this.

> these functions are not even exported and not necessarily called by the user as he will use setMBOControlTermination but anyhow if so we have to rename all of those

it is still beneficial to do this, I guess. Lets fix this things now.

**Pull request merged**
