### PR TITLE
add gg.objects to renderExampleRun functions

### PR DESCRIPTION
**Pull request by jakob-r**
This is very helpful if you want to modify the plots a bit (e.g. for publications). 
You can now pass different ggplot2 objects that will be added to each plot. 
Personally I favor `theme_bw()` which I now can easily apply to the MBO plots.

### CODE REVIEW

**Comment by berndbischl** [comment]
isnt this a bit strange API wise? and just bloat?

i can see your motivation, but why not simply create helper function, that can add the new ggplot objects to a bunch of plots after they are created? then you dont have to touch any of the existing functions, and it will work for other plots later.

 also this then does seem to have nothing to do with mbo? maybe put in BBmisc?
or can you name a use case where it would really help to have it in an arg like you did?

**Comment by jakob-r** [comment]
Because we use grid.extra and I am pretty sure even `print()`

**Comment by berndbischl** [comment]
> Because we use grid.extra and I am pretty sure even print()

the print i dont get where we would use that? please also note that we have the policy to return the individual plots in a list always via a render function, so you can do exactly the changes you want to do here, eg for publications. 

but i can kinda see you point. doing the grid.extra call then manually, later on, when the plots are ok in general, you just want a different theme, seems annoying. let me take a 2nd look.

**Comment by berndbischl** [comment]
1) please add at least one line to doc addGgsToGgplot

2) pls use a rox template for your new arg, you are copy-pasting

otherwise i guess we could merge

**Comment by berndbischl** [comment]
(if travis passes)

**Comment by jakob-r** [comment]
> please also note that we have the policy to return the individual plots in a list always via a render function, so you can do exactly the changes you want to do here, eg for publications.
With a bit of overhead you can do it without gg.objects but on the other hand `plotExampleRun` does quite a lot for you (including the printing) so I thought that you still want to use it. But then you could just use it there I guess.

**Comment by berndbischl** [comment]
like i said, i am not totally against this and can see your motivation to have this in for convenience.

**Comment by jakob-r** [comment]
Maybe you should have introduced a default for mlr:::getHyperParsString(... , show.missing.values) :wink: 
This was what broke travis. Will fix in master.

**Comment by jakob-r** [comment]
Now it works and I changed it to only work on plotExampleRun()

**Comment by jakobbossek** [comment]
looks good to me 👍

**Comment by berndbischl** [comment]
> Maybe you should have introduced a default for mlr:::getHyperParsString(... , show.missing.values)  
> This was what broke travis. Will fix in master.

i will repair this in mlr too, thx.

**Pull request merged**
