### PR TITLE
add explicit conversion of infill crit to character

### LINKED ISSUE #289: Arg Check for infill.crit does not work perfectly
```
ctrl = makeMBOControl()
ctrl = setMBOControlInfill(ctrl, crit = factor("ei"))
```

This should throw an error imo.

Just happened with batchtools. It's pretty annoying since this takes some time to debug and the error was not informative in my case.

### PR DESCRIPTION
**Pull request by jakobbossek**
Fixes #289.

### CODE REVIEW

**Comment by berndbischl** [comment]
unit test is missing

**Comment by jakobbossek** [comment]
@ja-thomas thx for the test.
AppVeyor error is due to randomness of tests. We can merge here.

**Comment by berndbischl** [comment]
i am not sure i like this. i rather would like to assert that only chars are allowed

**Comment by berndbischl** [comment]
@mllg does assertCoice now work better?

**Comment by berndbischl** [comment]
my preferred solution would be that assertChoice does not produce trouble here anymore and we dont have to change code like this

**Comment by mllg** [comment]
> my preferred solution would be that assertChoice does not produce trouble here anymore and we dont have to change code like this

You requested `assertChoice` to be more restrictive and now it is.

**Comment by berndbischl** [comment]
then lets clean up here or close pls. possibly we should simply keep the unit test as this has created too many problems

**Comment by mllg** [comment]
We keep the unit test and do the conversion. A future version of checkmate will give better error messages, but the conversion is safe to do nevertheless.

**Pull request merged**
