### PR TITLE
change default optim.method in km

### PR DESCRIPTION
**Pull request by ja-thomas**
Since rgenoud seems to create a constant kriging model a lot less frequent (see #258), I would suggest using it instead of BFGS. 

In my benchmarks it does not really improve mbo performance, but at least it looks nicer on exampleRun plots.

Also we had still a second version of km (RLearner_kmforrester) in our package, which wasn't touched for 2 years. I would guess that was used before mlr had km integrated? Since we never use it anywhere in the code I moved it to the ToDo files. If there is a good reason to keep it in the package let me know.

### CODE REVIEW

**Comment by jakob-r** [comment]
Seems valid. What have you found on this optimizer? DiceOptim also seems to use it. I wonder how it looks for higher dimensions, though.

From my side you can delete it. Seems to have been a try to make DiceKriging a bit more stable?

**Comment by berndbischl** [comment]
i think this is a good idea, but please 
a) document this and make it visible for the user (great. you did that, just a reminder in general)
b) we have to recompute for the paper then, but i guess we have to do that anyway

**Comment by jakob-r** [comment]
> b) we have to recompute for the paper then, but i guess we have to do that anyway

Do we? Did @ja-thomas use the mbo defaults? We could just say what exact learner we used. It is still repeatable.

**Comment by berndbischl** [comment]
> Do we? Did @ja-thomas use the mbo defaults? We could just say what exact learner we used. It is still repeatable.

well, its a bit strange if we don't compute that experiment in our official defaults. also its even more strange that we run all OTHER algos in their defaults, but in our case we would then deviate. 
(this is not about "repeatability" but "convincingness that what we do is reasonable")

**Comment by ja-thomas** [comment]
I would suggest that we run everything in the mlrMBO defaults. (All km based problems are quite fast to compute)

But before I rerun, we could also shortly talk about the defaults of the focus search

**Comment by berndbischl** [comment]
1) doc fix: its called "gen" and not "rgen" and we should better explain what that means (optimizing with rgenoud) and why we deviate (better, less constant models)

**Pull request merged**
