### PR TITLE
Switch to cmaesr

### PR DESCRIPTION
**Pull request by jakobbossek**

### CODE REVIEW

**Comment by jakobbossek** [comment]
Hmm, appveyor fails on the EA test which is not affected by the changes:
...
  OK: 453 SKIPPED: 1 FAILED: 1
  1. Failure: infillopt ea (@test_infill_opt_ea.R#13) 
  
  Error: testthat unit tests failed
  Execution halted
* DONE
...
Is this just due to randomized tests?

**Comment by berndbischl** [comment]
@jakobbossek 
is this work in progress? or COULD it be merged from your perspective if appveyor would run?

**Comment by berndbischl** [comment]
most important comment, otherwise code looks ok and changes seem trivial:
why do we use my super-naive restart strategy when your cmaesr offers IPOP restarts? 
why dont we simply enable those?

**Comment by berndbischl** [comment]
@jakobbossek 
in general please dont push RD files!

**Comment by berndbischl** [comment]
also: 
if done, please finally check that it is documented what happens with this infill optimizer for the user, i.e.
that the user can read that cmaesr (which what options?) is used.

**Comment by jakobbossek** [comment]
@berndbischl The `work in progress` label indicates work in progress 😉 
Regarding the restart strategy: I think we should stick to the independent restarts the `opt.restart` parameter is designed for and remember the user, that he can activate IPOP restarts via the `cmaes.control` object. What do you think?

**Comment by berndbischl** [comment]
> @berndbischl The work in progress label indicates work in progress

sure, just wanted to help with some intermediate comments. and it looked pretty good already.


> Regarding the restart strategy: I think we should stick to the independent restarts the opt.restart parameter is designed for and remember the user, that he can activate IPOP restarts via the cmaes.control object. What do you think?

i am fine with this. but is there a reason? what would you recommend as default, because that should, well, be the default.

**Comment by jakobbossek** [comment]
> >Regarding the restart strategy: I think we should stick to the independent restarts the opt.restart 
> >parameter is designed for and remember the user, that he can activate IPOP restarts via the
> >cmaes.control object. What do you think?

> i am fine with this. but is there a reason? what would you recommend as default, because that >should, well, be the default.

Well, `opt.restarts` is for *independent* restarts and IMO there should not be any special cases for certain optimizers regarding this, since the IPOP restarts are kind of not independent.

The default for IPOP restarts should be 0 since especially for large input dimensions the defaults for population size are quite high and restarts even double the population size which might take a long time then.

**Comment by berndbischl** [comment]
I am simply asking as I thought

a) the infill optimization in mbo will very likely be multimodal. so we need some restarts for CMAES?

b) i tought much work would have been invested into how to do this well, the restarting. and IPOP would have been one good option and result of that work? 
now you are saying you would not do that (by default)? just asking?

**Comment by jakobbossek** [comment]
> a) the infill optimization in mbo will very likely be multimodal. so we need some restarts for CMAES?

> b) i tought much work would have been invested into how to do this well, the restarting. and IPOP
>  would have been one good option and result of that work?
> now you are saying you would not do that (by default)? just asking?

Ok. These are good points. Maybe you are right and we should set `opt.restarts` to a value > 1 and use cmaes restarts in the special case of the cmaes optimzer instead of independent restarts?
However, what is a good value for the number of restarts and should restarts be enabled by default only for cmaes or the other optimizers as well?

**Comment by jakobbossek** [comment]
@berndbischl ping

**Comment by jakobbossek** [comment]
ping

**Comment by berndbischl** [comment]
> Ok. These are good points. Maybe you are right and we should set opt.restarts to a value > 1 and use cmaes restarts in the special case of the cmaes optimzer instead of independent restarts?

yes, thats what i meant.

> However, what is a good value for the number of restarts and should restarts be enabled by default only for cmaes or the other optimizers as well?

i have no idea. just take the default number of restarts we use for the focus search. or tell me more from the cmaes literature. but this is really a borderline case, we never really use the cmaes. so lets deal with this, doc it and close it soon pls

**Comment by jakobbossek** [comment]
@berndbischl Please have a final look and merge.

**Comment by berndbischl** [comment]
you did not doc how infill.opt.restarts affects the cmaes?

if you do this, this can be merged IMHO

do both pls

**Comment by jakobbossek** [comment]
Added docs. Merging.

**Pull request merged**
