### PR TITLE
Feature: Store infill components

### PR DESCRIPTION
**Pull request by jakob-r**
Regarding Issue #214 I now propose this method to store everything of interest in the opt.path.

### CODE REVIEW

**Comment by jakobbossek** [comment]
Looks ok.
However, IMHO the following part is a clear signal to make infill criteria more modular in future releases.
```splus
if (control$n.objectives == 1L && control$infill.crit == "ei") {
 +      prop$crit.components = data.frame(se = NA_real_, mean = NA_real_)
 +    } else if (control$n.objectives == 1L && control$infill.crit == "cb") {
 +      prop$crit.components = data.frame(se = NA_real_, mean = NA_real_, lambda = NA_real_)
 +    } else if (control$n.objectives == 1L && control$infill.crit == "aei") {
 +      prop$crit.components = data.frame(se = NA_real_, mean = NA_real_, tau = NA_real_)  
 +    }
...
```
Adding more infill criteria entails adding another two lines to this listing and maybe to some other files as well. I would like to have the following:
```splus
...
prop$crit.components = initInfillCritComponents(control$infill.crit)
...
```

**Comment by berndbischl** [comment]
have you documented this? the answer seems to be: no...

**Comment by jakob-r** [comment]
I am more likely to document if I get feedback about the chances that this will be integrated. So the answer is: With a better documentation you would merge?

**Comment by berndbischl** [comment]
> I am more likely to document if I get feedback about the chances that this will be integrated. So the answer is: With a better documentation you would merge?

sure, i mean what is the downside? you just make more info available posthoc?
that seems always good....

**Pull request merged**
