### PR TITLE
Fix Issue #407 scalarize parego infill

### PR DESCRIPTION
**Pull request by jakob-r**
Fixes Issue #407. Scalarization parameters are now passed in the control object and transformed by a universal function

### CODE REVIEW

**Comment by jakob-r** [comment]
* improve internal documentation of convertToDesign
* rename convertOptPathToDf.R

**Comment by jakob-r** [comment]
Locally the tests pass now

**Comment by ja-thomas** [comment]
What is the state here?

I think we need that fix for the multiobj benchmark.

@berndbischl @danielhorn can one of you have a look, you're familiar with the multiobjective stuff, or at least not familiar enough to see what's going on here.

**Comment by jakob-r** [comment]
Okay- test are just failing for Appveyor R devel. That should be fine.

**Pull request merged**
