### PR TITLE
fix broken multifid example plot

### PR DESCRIPTION
**Pull request by jakob-r**
changes went undetected here as it seems

### CODE REVIEW

**Comment by berndbischl** [comment]
1) travis fails

2) please add at least a mini test that touches the relevant part of the code
you yourself said:

> changes went undetected here as it seems

**Comment by jakob-r** [comment]
As it's part of the examples it's already included in the checks. I think travis somehow gave us a false positive.

**Comment by jakob-r** [comment]
I don't know whats going on in Travis here

**Comment by berndbischl** [comment]
> As it's part of the examples it's already included in the checks.

huh? why? isnt that actually a problem? where is the code part that runs our examples in that folder? 
i mean there is no "magic" that does that, just because we call the folder "examples".
are you confusing this with the "@examples" from roxygen?

**Comment by berndbischl** [comment]
we just discovered that we have code to run examples under "tests". 
i have turned this on for travis now.

merging this now so it runs

**Pull request merged**
