### PR TITLE
fix issue #331 infillcrits

### PR DESCRIPTION
**Pull request by jakob-r**
Should fix all issues in #331.
Can we allow more infill-crits in `setMBOControlMultiObj`?

### CODE REVIEW

**Comment by berndbischl** [comment]
\code{MBOInfillCriterion}]\

use code + link in these cases

otherwise i think we can merge

@jakobbossek @ja-thomas 

can you pls check too

**Comment by berndbischl** [comment]
do you want a review or not done?

**Comment by ja-thomas** [comment]
Looks good

**Comment by jakob-r** [comment]
Yes. Ready to be reviewed :fried_egg:

**Comment by berndbischl** [comment]
1) thanks!

- fixed some typos (dont use title style / capital letters in normal english text...)

- removed some objects, we dont need 5 different lambda-crits....

**Comment by berndbischl** [comment]
fixing locally some minor stuff, pls merge when travis green (later, still on it)

**Comment by berndbischl** [comment]
done, pls merge soon if green

**Pull request merged**
