### PR TITLE
pass show.info to show.learner.output (Fixes #378)

### LINKED ISSUE #378: mbo(..., show.info = FALSE) should affect mlr output
if no learner is given show.info should affect the output of the learner as well.

### PR DESCRIPTION
**Pull request by jakob-r**
#378

### CODE REVIEW

**Comment by berndbischl** [comment]
i dont think that checkLearner is the correct place to introduce that extra option.

just put it into makeMBOLearner?

**Comment by berndbischl** [comment]
also you are using getOptIon many times in your code, you should do this exactly once!
when you call makeMBOLearner

**Comment by berndbischl** [comment]
you also have not added a test, that shows that your PR improves the current behavior

**Comment by berndbischl** [comment]
i am not even sure whether we should entangle all of this. this looks like generally bad code. 

what you did good is to add the option "config" to makeMBOLearner. that allows more control to the user. 
learner output is then controlled by mlr. 

isnt that well defined then?

**Comment by jakob-r** [comment]
1. If I put it only in `makeMBOLearner` I cannot pass the `show.info` that I got when I called `mbo(..., show.info = FALSE)`

2. I just put `getOption("mlrMBO.show.info", TRUE)` in the head of the functions `exampleRun` and `exampleRunMultiObj` where it was previously just a bit more "hidden". The `show.info` is also not only of interest for the learner but also for the output of mbo itself

3. I have already added a test, that checks that no output is generated. But I can add a test, checks whether output is generated by the learner if `show.info = TRUE`? :confused: I am not entirely sure what a useful test would be. Can you elaborate?

4. The user does not always call `makeMBOLearner`. Instead a normal use case would be to call `mbo(fun, control = ctrl, show.info = FALSE)`. In this case the user obiously does not want to see any additional info. Accordingly the learner should be silent.

**Comment by berndbischl** [comment]
lets get the general API right, then discuss details, ok?

so the issue you are trying to resolve here is (please correct me if wrong)

a user calls mbo, normal usecase is to have the default learner being constructed internally. 
now mlr outputs lots of crap during training of eg regr.km. as the learner is constructed internally, i have no chance to influence this

more comments on this:
- if i call makeMBOLearner manually, i can possibly set the mlr config options of the learner. especially, in this PR as you added "config" as a new arg for makeMBOLearner. this is why i said this is "good".
but like i said, normally i want to have the default learner being constructed silently internally

- show.info of mbo controls the output of mbo itself. the mlr option controls the output of the mlr learner. 
this seems well defined and we want to keep that?

- now when the normal default learner is constructed internally, you still need to somehow set a reasonable option for show.info of the learner, right?

in that case, i would simply set config = NULL as default. in makeMBOLEarner. then use the defaults of configureMlr here. actually those are already used? and you can always write
configureMlr at the top of your script? or manually call makeMBOLearner with your own config options?

this is why i think this PR looks like "bad feature creep"?

**Comment by jakob-r** [comment]
Yes. You got everything right. And as also shown in the vignette files, `configureMlr` is the solution. But seen from the users perspective: If he chooses to see no info he does not expect any info. So all underlying methods should inherit the behavior from their root.

An easy solution: We construct "regr.km" with `show.learner.output = FALSE` by default.

**Comment by berndbischl** [comment]
> But seen from the users perspective: If he chooses to see no info he does not expect any info. So all underlying methods should inherit the behavior from their root.

but you have to understand that "output" here is generated by different systems and components.

> An easy solution: We construct "regr.km" with show.learner.output = FALSE by default

see, this sounds good. and we add the "config" option, like you did. and doc im mbo that the learner output in controlled via the mlr options

**Pull request merged**
