### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by jakob-r**
Really minor fixes on Issue #204 and #190. You have one week for veto before I will auto-merge :wink:

### CODE REVIEW

**Comment by berndbischl** [comment]
why does travis now fail?

**Comment by berndbischl** [comment]
please also use the new arg for hasDiscrete.

(yes, just pulled it in now)

https://github.com/berndbischl/ParamHelpers/pull/91

**Comment by jakob-r** [comment]
Checks pass now

**Comment by berndbischl** [comment]
thx. well done

**Pull request merged**
