### PR TITLE
renamed .weight to parEGOweight

### PR DESCRIPTION
**Pull request by ja-thomas**
See #242

### CODE REVIEW

**Comment by ja-thomas** [comment]
Hm, the failing tests are working locally, but give a warning

```
Warnings -----------------------------------------------------------------------
1. plot multi crit (@test_plot_MBOResult.R#30) - Removed 2 rows containing missing values (geom_point).

2. plot multi crit (@test_plot_MBOResult.R#30) - Removed 2 rows containing missing values (geom_path).

3. plot multi crit (@test_plot_MBOResult.R#30) - Removed 2 rows containing missing values (geom_point).

4. plot multi crit (@test_plot_MBOResult.R#30) - Removed 2 rows containing missing values (geom_path).
```

**Comment by jakob-r** [comment]
I will investigate next week.

**Comment by ja-thomas** [comment]
Ok, so the errors are again stochastic, see #238

**Comment by berndbischl** [comment]
could you pls as all other names in "extras" seem to be lower case name this "parego.weights.j" ?
sorry.

**Comment by ja-thomas** [comment]
@berndbischl I think you can merge? Then the master should not fail anymore

**Pull request merged**
